from selenium import webdriver


driver = webdriver.Chrome()
driver.get("https://buggy-testingcup.pgs-soft.com/")
driver.find_element_by_xpath("//h2[contains(.,'Zadanie 1')]").click()
driver.find_element_by_xpath("html/body/div[1]/div/div/div[2]/div[1]/a").click()
driver.find_element_by_xpath("html/body/div[1]/div/div[2]/div[1]/form/div[1]/div[1]/div/div/div/input").clear()
driver.find_element_by_xpath("html/body/div[1]/div/div[2]/div[1]/form/div[1]/div[1]/div/div/div/input").send_keys("3")
driver.find_element_by_xpath("//button[@data-product-name='Okulary']").click()
driver.find_element_by_xpath("html/body/div[1]/div/div[2]/div[1]/form/div[1]/div[2]/div/div/div/input").clear()
driver.find_element_by_xpath("html/body/div[1]/div/div[2]/div[1]/form/div[1]/div[2]/div/div/div/input").send_keys("2")
driver.find_element_by_xpath("//button[@data-product-price='39.22']").click()
driver.find_element_by_xpath("html/body/div[1]/div/div[2]/div[1]/form/div[3]/div[3]/div/div/div/input").clear()
driver.find_element_by_xpath("html/body/div[1]/div/div[2]/div[1]/form/div[3]/div[3]/div/div/div/input").send_keys("1")
driver.find_element_by_xpath("//button[@data-product-name='Zeszyt']").click()
driver.find_element_by_xpath("html/body/div[1]/div/div[2]/div[1]/form/div[3]/div[4]/div/div/div/input").clear()
driver.find_element_by_xpath("html/body/div[1]/div/div[2]/div[1]/form/div[3]/div[4]/div/div/div/input").send_keys("4")
driver.find_element_by_xpath("//button[@data-product-name='Kostka']").click()
driver.find_element_by_xpath("html/body/div[1]/div/div[2]/div[1]/form/div[2]/div[2]/div/div/div/input").clear()
driver.find_element_by_xpath("html/body/div[1]/div/div[2]/div[1]/form/div[2]/div[2]/div/div/div/input").send_keys("8")
driver.find_element_by_xpath("//button[@data-product-name='Kamera']").click()
driver.find_element_by_xpath("html/body/div[1]/div/div[2]/div[1]/form/div[2]/div[1]/div/div/div/input").clear()
driver.find_element_by_xpath("html/body/div[1]/div/div[2]/div[1]/form/div[2]/div[1]/div/div/div/input").send_keys("5")
driver.find_element_by_xpath("//button[@data-product-name='Słuchawki']").click()
driver.find_element_by_xpath("html/body/div[1]/div/div[2]/div[1]/form/div[1]/div[4]/div/div/div/input").clear()
driver.find_element_by_xpath("html/body/div[1]/div/div[2]/div[1]/form/div[1]/div[4]/div/div/div/input").send_keys("7")
driver.find_element_by_xpath("//button[@data-product-name='Kabel']").click()
driver.find_element_by_xpath("html/body/div[1]/div/div[2]/div[1]/form/div[2]/div[3]/div/div/div/input").clear()
driver.find_element_by_xpath("html/body/div[1]/div/div[2]/div[1]/form/div[2]/div[3]/div/div/div/input").send_keys("9")
driver.find_element_by_xpath("//button[@data-product-name='Aparat']").click()
print("test ok")
driver.quit()